"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TOGGLEJSVALIDATOR = exports.TOGGLEACMSCSS = exports.SETUNITGROUPTITLENAME = exports.SETTAG = exports.SETSTATE = exports.SETGROUPTITLENAME = exports.RESTORE = exports.CLEARUNITGROUPTITLENAME = exports.CLEARUNITGROUPITEM = exports.CLEARGROUPITEM = exports.CLEARCUSTOMUNIT = exports.CLEARCUSTOMFIELD = exports.CHANGEDIRECTION = exports.ADDUNITGROUPITEM = exports.ADDSNIPPET = exports.ADDGROUPITEM = exports.ADDCUSTOMUNIT = exports.ADDCUSTOMFIELD = void 0;
var ADDCUSTOMFIELD = exports.ADDCUSTOMFIELD = 'ADDCUSTOMFIELD';
var ADDGROUPITEM = exports.ADDGROUPITEM = 'ADDGROUPITEM';
var SETGROUPTITLENAME = exports.SETGROUPTITLENAME = 'SETGROUPTITLENAME';
var SETUNITGROUPTITLENAME = exports.SETUNITGROUPTITLENAME = 'SETUNITGROUPTITLENAME';
var ADDCUSTOMUNIT = exports.ADDCUSTOMUNIT = 'ADDCUSTOMUNIT';
var ADDUNITGROUPITEM = exports.ADDUNITGROUPITEM = 'ADDUNITGROUPITEM';
var CLEARCUSTOMFIELD = exports.CLEARCUSTOMFIELD = 'CLEARCUSTOMFIELD';
var CLEARGROUPITEM = exports.CLEARGROUPITEM = 'CLEARGROUPITEM';
var CLEARCUSTOMUNIT = exports.CLEARCUSTOMUNIT = 'CLEARCUSTOMUNIT';
var CLEARUNITGROUPITEM = exports.CLEARUNITGROUPITEM = 'CLEARUNITGROUPITEM';
var CLEARUNITGROUPTITLENAME = exports.CLEARUNITGROUPTITLENAME = 'CLEARUNITGROUPTITLENAME';
var SETTAG = exports.SETTAG = 'SETTAG';
var TOGGLEACMSCSS = exports.TOGGLEACMSCSS = 'TOGGLEACMSCSS';
var TOGGLEJSVALIDATOR = exports.TOGGLEJSVALIDATOR = 'TOGGLEJSVALIDATOR';
var RESTORE = exports.RESTORE = 'RESTORE';
var ADDSNIPPET = exports.ADDSNIPPET = 'ADDSNIPPET';
var SETSTATE = exports.SETSTATE = 'SETSTATE';
var CHANGEDIRECTION = exports.CHANGEDIRECTION = 'CHANGEDIRECTION';