'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var ADDCUSTOMFIELD = exports.ADDCUSTOMFIELD = 'ADDCUSTOMFIELD';
var ADDGROUPITEM = exports.ADDGROUPITEM = 'ADDGROUPITEM';
var SETGROUPTITLENAME = exports.SETGROUPTITLENAME = 'SETGROUPTITLENAME';
var SETUNITGROUPTITLENAME = exports.SETUNITGROUPTITLENAME = 'SETUNITGROUPTITLENAME';
var ADDCUSTOMUNIT = exports.ADDCUSTOMUNIT = 'ADDCUSTOMUNIT';
var ADDUNITGROUPITEM = exports.ADDUNITGROUPITEM = 'ADDUNITGROUPITEM';
var CLEARCUSTOMFIELD = exports.CLEARCUSTOMFIELD = 'CLEARCUSTOMFIELD';
var CLEARGROUPITEM = exports.CLEARGROUPITEM = 'CLEARGROUPITEM';
var CLEARCUSTOMUNIT = exports.CLEARCUSTOMUNIT = 'CLEARCUSTOMUNIT';
var CLEARUNITGROUPITEM = exports.CLEARUNITGROUPITEM = 'CLEARUNITGROUPITEM';
var CLEARUNITGROUPTITLENAME = exports.CLEARUNITGROUPTITLENAME = 'CLEARUNITGROUPTITLENAME';
var TOGGLEACMSCSS = exports.TOGGLEACMSCSS = 'TOGGLEACMSCSS';
var TOGGLEJSVALIDATOR = exports.TOGGLEJSVALIDATOR = 'TOGGLEJSVALIDATOR';
var RESTORE = exports.RESTORE = 'RESTORE';
var ADDSNIPPET = exports.ADDSNIPPET = 'ADDSNIPPET';
var SETSTATE = exports.SETSTATE = 'SETSTATE';